# Generated by Django 6.1 on 2026-08-21 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_id', models.CharField(max_length=50, unique=True)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=150)),
                ('today_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('available_inventory', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
