# Generated by Django 6.1 on 2026-08-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('distributor_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('usertype', models.CharField(default='distributor', max_length=20)),
                ('today_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('available_inventory', models.IntegerField(default=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='DistributorProfile',
        ),
    ]
