# Generated by Django 6.1 on 2026-08-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_user_delete_distributorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=150)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
